<div class="form">
    <form action="/autenticar" method="POST" class="login" id="login">
        <hgroup>
            <h2>Login</h2>
        </hgroup>
    
        <label for="email">Email</label>
        <input type="email" id="email" name="email" class="input" placeholder="Seu email" required autofocus><br>

        <label for="senha">Senha</label>
        <input type="password" id="senha" name="senha" class="input" placeholder="Senha" required><br>
        <button type="submit" id="entrar" class="btn btn-success">Entrar</button><br>
        <p class="mt-3 mb-3">&copy; 2022-2023</p>
    </form>
</div>