<div class="form">
    <form action="/cadastrar" method="POST" class="login">
        <h2 class="h2 p-3">Cadastro de novo Usuário</h2>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
            </div>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="nome curto">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">Email</span>
            </div>
            <input type="text" class="form-control" id="email" name="email" placeholder="seu melhor">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">Senha</span>
            </div>
            <input type="password" class="form-control" id="senha" name="senha" placeholder="**********">
        </div>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <span class="input-group-text">Admin:</span>
            </div>
            <select name="admin" id="admin">
                <option value="0">Não permitir</option>
                <option value="1">Permitir</option>
            </select>
        </div>
        <button type="submit" class="btn btn-success p-2 m-2">Cadastrar</button><br>
        <a href='/patrimonio' class="btn btn-outline-light">Voltar</a>
        <p>&copy; 2022-2023</p>
    </form>
</div>