<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Patrimônio Histórico</title>
	
	<link rel="shortcut icon" href="img/logo.png" type="image/x-icon">
	<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
	
	<link rel="stylesheet" href="css/bootstrap.css">
	<?php
		$links = $this->css();
		foreach($links as $link){
			echo $link;
		}
	?>
</head>

<body>

	<?= $this->content() ?>

</body>
</html>